# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NSStringKitCode' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NSStringKitCode

  target 'NSStringKitCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NSStringKitCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
